### ISSUE TITLE
Getting an error TypeError: Cannot read property 'Hash' of undefined

### ISSUE THREAD

**Issue by ashishchandr70** [moneybutton/express-paymail#14]
Hi,

Here is my code snippet for using @moneybutton/express-paymail:

```
import { Address, Bip32, Ecdsa, Hash, PubKey, Sig } from 'bsv';
import { buildRouter } from '@moneybutton/express-paymail';
import cors from 'cors';
import crypto from 'crypto';
import express, { Request, Response, NextFunction } from 'express';
import createError from 'http-errors';
import morgan from 'morgan';

const paymailRouter = buildRouter(API, {
  basePath: '/api/bsvalias',
  getIdentityKey: async (name, domain) => {
    // A paymail has the form `name@domain`. You can find the appropiate
    // key using paymail data.
    return '0335e5e7b86c12a4b5df082acb43ca7805382b58c805172bdef20ced310df845aa' // Some public key
  },
  getPaymentDestination: async (name, domain, body, helpers) => {
    // This method have to return a valid bitcoin outputs. The third parameter is the
    // body of the request and the fourth parameter is a js object containing handful
    // methods to create outputs.
    return helpers.p2pkhFromAddress('1FJJkRqyxTKAVX3dGFpddERt9XRbiSRZkL')
  },
  verifyPublicKeyOwner: async (name, domain, publicKeyToCheck) => {
    // Returns true if the public key belongs to the user owning `name@domain`, false in
    // any other case.
    return '0335e5e7b86c12a4b5df082acb43ca7805382b58c805172bdef20ced310df845aa' === publicKeyToCheck
  }
})

app.enable('trust proxy');
app.use(cors());
app.use(express.json());
app.use(paymailRouter);
app.use((req, res, next) => {
    (req as any).id = `${Date.now()}-${Math.round(Math.random() * 10 ** 6)}`;
    next();
});
morgan.token('id', (req) => (req as any).id);
app.use(morgan(':id :method :url :status :res[content-length] - :response-time ms ":user-agent"'))

app.get('/', (req, res, next) => {
    res.status(200).send("UP");
});

app.get('/health', (req, res, next) => {
    res.status(200).send("UP");
});

app.listen(PORT || 8080, () => {
        console.log(`listening on *:${PORT}`);
});

```
However, when I run this, I get the following error:

**$ ./node_modules/.bin/ts-node paymail.ts** 

```
/usr/local/src/Kronoverse/krono-stacks/docker/paymail/node_modules/@moneybutton/brfc/src/index.js:11
  let hash = bsv.crypto.Hash.sha256sha256(
                        ^
TypeError: Cannot read property 'Hash' of undefined
    at Object.brfc (/usr/local/src/Kronoverse/krono-stacks/docker/paymail/node_modules/@moneybutton/brfc/src/index.js:11:25)
    at Object.<anonymous> (/usr/local/src/Kronoverse/krono-stacks/docker/paymail/node_modules/@moneybutton/paymail-client/src/constants.js:6:28)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/usr/local/src/Kronoverse/krono-stacks/docker/paymail/node_modules/@moneybutton/express-paymail/lib/buildGetPaymentDestinationRouter.js:28:22)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
```

Am I doing something wrong?

Thank you
Ashish

**Comment by ashishchandr70** [comment]
I was mixing up versions of bsv. It needs to be v1.5.0 used by @moneybutton/express-paymail.
